env_name: "SberInvertedPendulum-v0"
experiment_name: "experiment_0"

ppo_params:
  gamma: 0.99
  lam: 0.95
  clip_eps_start: 0.1 #0.2
  clip_eps_max: 0.2
  clip_eps_min: 0.05
  lr: 0.000003   #0.00003
  entropy_coef: 0.1 # 0.0001
  episodes: 100000
  update_epochs: 2
  batch_size: 512
  print_reward_every: 10
  max_episode_steps: 2000
  kl_treshold: 0.01 #0.01

log_params:
  log_dir: "runs/ppo_run"
  
checkpoint_params:
  save_model_every: 50
